import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import java.math.BigDecimal;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by '1011425' at '7/25/16 12:08 PM' with Gradle 2.14.1
 *
 * @author 1011425, @date 7/25/16 12:08 PM
 */
public class BankAccountTest {
	
	BankAccount account;
	BigDecimal initBal;
	BigDecimal deposit;
	
	@Before
	public void setup() throws Exception{
		initBal = new BigDecimal(500.00).setScale(2, BigDecimal.ROUND_HALF_UP);
		account = new BankAccount(initBal);
		deposit = new BigDecimal(25.43).setScale(2, BigDecimal.ROUND_HALF_UP);
	}
	
    @Test public void testAccount() {
        assertNotNull(initBal);
        assertNotNull(account);
        assertEquals(initBal, account.getBalance());
    }
    
    @Test public void testDeposit() {
        assertNotNull(deposit);
        assertNotNull(account);
        account.deposit(deposit);
        BigDecimal expBal = new BigDecimal(525.43).setScale(2, BigDecimal.ROUND_HALF_UP);
        assertEquals(expBal, account.getBalance());
    }
}
