/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '1011425' at '7/25/16 12:08 PM' with Gradle 2.14.1
 *
 * @author 1011425, @date 7/25/16 12:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
